name: genopandas-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Package requirements.
  - python =3.6
  - pandas
  - intervaltree
  - toolz
  - natsort

  # Development requirements.
  - pytest
  - pylint
  - yapf
  - sphinx

  - pip:
    # Package requirements.
    - pysam

    # Development requirements.
    - pytest-helpers-namespace
    - spinx-autobuild
    - sphinx_rtd_theme
